### NumPy
NumPy es el módulo más usado para cálculo científico en Python

In [ ]:
import numpy as np

El objeto principal de Numpy es un array homogéneo multidimensional. Básicamente se trata de una tabla de elementos (generalmente números) todos del mismo tipo (ésta es una diferencia en cuantoa las listas, que permitían tipos mezclados) que se encuentran indizados (indexados). Las dimensiones del array en Numpy se denominan ejes (axes).

La clase base del array es `ndarray` (lo que Python nos devuelve si usamos la función `type` sobre un array.

Los atributos principales de un array son:

- **ndarray.ndim**: la cantidad de ejes
- **ndarray.shape**: La "forma" del array, es decir, sus dimensiones. Es una n-upla de enteros que nos dice la dimensión del array en cada eje. Por ejemplo, para una matriz de n filas y m columnas shape será `(n,m)` (existiendo un sólo eje o axis). La longitud de la forma `shape` será la cantidad de ejes que tengamos, es decir `ndim`. Podríamos tener en un mismo array varias matrices una en cada eje.
- **ndarray.size**: Cantidad de elementos en el array.
- **ndarray.dtype**: El tipo de datos que contiene el array.
- **ndarray.itemsize**: El tamaño (en bytes) de los elementos del array

In [ ]:
a = np.arange(15) #array de numeros 0 a 14
a

In [ ]:
a.dtype

In [ ]:
print(a)

In [ ]:
print(a.shape)

In [ ]:
print(a.ndim)

In [ ]:
print(a.dtype.name)

In [ ]:
print(a.itemsize)

In [ ]:
print(a.size)

In [ ]:
print(type(a))

#### Creando un array

Se puede crear un array desde una lista o tupla de Python al usar la función array. El tipo de array resultante se decude de los elementos de la lista.

Un error común es pasar directamente los valores del array a la función,

```
a = np.array(1,2,3,4)   # MAL
a = np.array([1,2,3,4]) # BIEN
a = np.array((1,2,3,4))  # BIEN
```

In [ ]:
b = np.array([6, 7, 8])
print(b)

In [ ]:
print(type(b))

`array` también puede transformar conjuntos de tuplas o secuencias de secuencias en arreglos n-dimensionales. Por ejemplo:

In [ ]:
c = np.array([(1.5, 2 ,3), (4, 5, 6), (7.1, 7.2, 7.3)])
print(c)

In [ ]:
print(c.shape)

La función `zeros` crea un array de ceros, la función `ones` crea un array de unos y la función  `random.rand` crea un array de valores `float` aleatorios en el intervalo [0,1] mientras que la función `empty` crea un array cuyo contenido depende de lo que haya en memoria (sinceramente nunca usé esta función) con el tipo `float64`.

Existen otras funciones como `zeros_like` que crea arrays del tamaño de otro objeto, útil cuando queremos que dos arrays tengan el mismo tamaño.

In [ ]:
np.zeros((3,4))

In [ ]:
test = np.ones((2,3,4), dtype=np.int16)
print(test)

In [ ]:
np.random.rand(3,2)
B = np.random.rand(3,2)

In [ ]:
np.empty((2,3)) # uninitialized, output may vary

In [ ]:
C =np.zeros_like(B)
np.size(C)
print(C)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


NumPy provee algunas funciones para crear arrays de tamaño o paso predefinido. La función `arange` crea arrays de la siguiente manera

In [ ]:
np.arange( 10, 30, 5 ) # array de 10 a 30 con un paso de 5 (de 5 en cinco)

array([10, 15, 20, 25])

Otra función es `linspace` que hace algo similar

In [ ]:
np.linspace(0,10,20) # inicio, fin, cantidad de elementos

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

#### Manipulación de arrays

Las funciones típicas son:
- `ravel()` aplana el array
- `reshape()` cambia la forma
- `transpose()` lo transpone

In [ ]:
example = np.random.rand(4,4)
print(example)

[[0.76567456 0.89133468 0.24932026 0.68175576]
 [0.28769869 0.37903078 0.21482535 0.10181396]
 [0.66248563 0.22776659 0.06954442 0.65318739]
 [0.97281025 0.51268667 0.84836693 0.600809  ]]


In [ ]:
example*10

array([[7.65674557, 8.91334678, 2.49320258, 6.81755759],
       [2.87698686, 3.79030783, 2.14825349, 1.01813956],
       [6.62485635, 2.27766588, 0.6954442 , 6.53187385],
       [9.7281025 , 5.12686673, 8.48366935, 6.00809002]])

In [ ]:
example_flat = example.ravel()  # devuelve el array, "aplanado"
print(example_flat)

[0.76567456 0.89133468 0.24932026 0.68175576 0.28769869 0.37903078
 0.21482535 0.10181396 0.66248563 0.22776659 0.06954442 0.65318739
 0.97281025 0.51268667 0.84836693 0.600809  ]


In [ ]:
example_flat.reshape(2,8) # devuelve el array pero como una matriz de 2x8

array([[0.76567456, 0.89133468, 0.24932026, 0.68175576, 0.28769869,
        0.37903078, 0.21482535, 0.10181396],
       [0.66248563, 0.22776659, 0.06954442, 0.65318739, 0.97281025,
        0.51268667, 0.84836693, 0.600809  ]])

In [ ]:
example_flat.reshape(4,4) # devuelve el array a su forma original

array([[0.76567456, 0.89133468, 0.24932026, 0.68175576],
       [0.28769869, 0.37903078, 0.21482535, 0.10181396],
       [0.66248563, 0.22776659, 0.06954442, 0.65318739],
       [0.97281025, 0.51268667, 0.84836693, 0.600809  ]])

In [ ]:
test = np.random.rand(2,3,6)
print(test)

[[[0.61009191 0.952007   0.77818219 0.91818426 0.01325187 0.84426923]
  [0.2999295  0.11685055 0.66988619 0.83109041 0.41411909 0.83161652]
  [0.60303521 0.00812555 0.89188611 0.00854006 0.08885923 0.06199936]]

 [[0.6950938  0.12561522 0.37506632 0.87337173 0.82233954 0.26800269]
  [0.47610447 0.5304494  0.67729577 0.29651654 0.00721179 0.83393593]
  [0.0146143  0.44131508 0.64560129 0.19333913 0.97524196 0.86407108]]]


In [ ]:
print(test.ravel())

[0.61009191 0.952007   0.77818219 0.91818426 0.01325187 0.84426923
 0.2999295  0.11685055 0.66988619 0.83109041 0.41411909 0.83161652
 0.60303521 0.00812555 0.89188611 0.00854006 0.08885923 0.06199936
 0.6950938  0.12561522 0.37506632 0.87337173 0.82233954 0.26800269
 0.47610447 0.5304494  0.67729577 0.29651654 0.00721179 0.83393593
 0.0146143  0.44131508 0.64560129 0.19333913 0.97524196 0.86407108]


In [ ]:
print(example.transpose())

[[0.76567456 0.28769869 0.66248563 0.97281025]
 [0.89133468 0.37903078 0.22776659 0.51268667]
 [0.24932026 0.21482535 0.06954442 0.84836693]
 [0.68175576 0.10181396 0.65318739 0.600809  ]]



Buscar las funciones que permiten en numpy calcular:

*  el valor medio
*  la desviación estándar
*  La sumatoria de un array
*  El valor máximo de un array
*  El valor mínimo de un array

